### ISSUE TITLE
Enable emailing system so that users can use the Forgot your password? feature

### ISSUE THREAD

**Issue by simaob** [simaob/posso-ir-api#52]

**Comment by simaob** [comment]
Hey, any of you recommends a specific service to send emails from the app on EC2?

**Comment by hugopeixoto** [comment]
There's AWS SES, if you want to stay inside the AWS ecosystem. Never used it much, but it should be straightforward:
https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/SES/Client.html#send_email-instance_method

Other than that, I only used sendgrid. Its ruby gem is a bit quirky, but works.

**Comment by simaob** [comment]
does it require setup on the server, or just creating an account? Maybe that's simplest?

**Comment by hugopeixoto** [comment]
To use SES, you need to either:
- create an access key & secret pair, put it on the app ENV
- create a policy and attach it to a role that's assumed by the EC2 instance

I would suggest using the same AWS account, not creating another one. The fewer the better

**Comment by hugopeixoto** [comment]
The policy would be something like this:

```
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Effect":"Allow",
      "Action":[
        "ses:SendEmail",
        "ses:SendRawEmail"
      ],
      "Resource":"*"
    }
  ]
}
```

(from https://docs.aws.amazon.com/ses/latest/DeveloperGuide/control-user-access.html)

**Comment by simaob** [comment]
OK, I need to get the access rights to the AWS account, I don't have at the moment. I'll check with Tiago.

**Comment by hugopeixoto** [comment]
I can set up the EC2 role thing in the `infrastructure` terraform repository. That way it'll be version controlled instead of clicked through.

**Comment by simaob** [comment]
Please do! 🙏

**Comment by hugopeixoto** [comment]
https://github.com/posso-ir/backend-infrastructure/pull/5

I'm not sure if this works. I will apply it. Can you test it from the instance directly? You'll need the `aws-sdk-ses` gem, probably.

**Comment by simaob** [comment]
I'll check the gem and try to set it up and test it. Is this active already?

**Comment by hugopeixoto** [comment]
Yes, I just ran `terraform apply`. You can try this by installing `awscli` in the server and running:

```
aws ses send-email --from 'hugo@posso-ir.com' --region eu-west-1 --destination='ToAddresses=hugo.peixoto@gmail.com' --message '{"Subject":{"Data":"Hello"},"Body":{"Text":{"Data":"Potato"}}}'
```

The `from` address must be `@posso-ir.com`.

**Comment by simaob** [comment]
Done! =) Thanks for your help!

**Comment by hugopeixoto** [comment]
Something that might be relevant: If you want to send emails from domains other than posso-ir.com, they'll need to be validated. This one was already validated, for some reason :shrug:

**Comment by simaob** [comment]
We already had customer support and some other emails working for the domain, that's probably why. Not sure we need to send the emails from the other domains yet. I did change the default_url_host to be dynamic, so that people from the spanish site will get the right links.
